import Ember from 'ember';

export default Ember.Controller.extend({
  uiColors: [
    { name: "themePrimaryColor", value: "#F2C811" },
    { name: "themeDarkColor", value: "#CDA521" },
    { name: "themeDarkerColor", value: "#BE9A27" },
    { name: "themeSecondaryColor", value: "#000000" },
    { name: "themeSecondaryAltColor", value: "#444444" },

    { name: "neutralDarkColor", value: "#212121" },

    { name: "neutralPrimaryColor", value: "#333333" },
    { name: "neutralPrimaryColorAlt", value: "#444444" },
    { name: "neutralPrimaryColorAlt2", value: "#4a4a4a" },
    { name: "neutralPrimaryColorAlt3", value: "#515151" },

    { name: "neutralSecondaryColor", value: "#666666" },
    { name: "neutralSecondaryAltColor", value: "#777777" },
    { name: "neutralSecondaryAltColor2", value: "#888888" },

    { name: "neutralTertiaryColor", value: "#A6A6A6" },
    { name: "neutralTertiaryAltColor", value: "#C8C8C8" },

    { name: "neutralLightColor", value: "#EAEAEA" },
    { name: "neutralLighterColor", value: "#F4F4F4" },

    { name: "blackColor", value: "#000000" },
    { name: "whiteColor", value: "#FFFFFF" },
    { name: "linkColor", value: "#000000" },
    { name: "highlightColor", value: "#FFEE80" },
    { name: "warningColor", value: "#E81123" },
    { name: "successColor", value: "#3bb44a" },
    { name: "infoColor", value: "#DEEBF6" },
    { name: "infoDarkColor", value: "#33669A" },
    { name: "alertColor", value: "#FFF9AE" },
    { name: "alertDarkColor", value: "#DDB53B" },
    { name: "alertBorderColor", value: "#D7D889" },
    { name: "criticalColor", value: "#FADBD2" },
    { name: "questionBoxForegroundColor", value: "#999999" }
  ],

  visualColors: [
    { name: "dataColor1", value: "#01B8AA" },
    { name: "dataColor2", value: "#374649" },
    { name: "dataColor3", value: "#FD625E" },
    { name: "dataColor4", value: "#F2C80F" },
    { name: "dataColor5", value: "#5F6B6D" },
    { name: "dataColor6", value: "#8AD4EB" },
    { name: "dataColor7", value: "#FE9666" },
    { name: "dataColor8", value: "#A66999" },
    { name: "dataColor9", value: "#3599B8" },
    { name: "dataColor10", value: "#DFBFBF" },
    { name: "negativeColor", value: "#FD625E" },
    { name: "neutralColor", value: "#F2C80F" },
    { name: "positiveColor", value: "#01B8AA" },
  ],

  standardGlyphs: [
    "share",
    "save",
    "saveas",
    "financial",
    "edit",
    "emi",
    "checkboxcomposite",
    "checkmark",
    "page2",
    "folder",
    "link",
    "group",
    "paste",
    "emoji",
    "upload",
    "pc1",
    "add",
    "search",
    "globalnavbutton",
    "pageright",
    "pageleft",
    "tvmonitor",
    "chromerestore",
    "world",
    "more",
    "slideshow",
    "photo",
    "calendar",
    "favoritestar",
    "collection",
    "chromefullscreen",
    "undo",
    "back",
    "font",
    "flickup",
    "chromeminimize",
    "gripperbarhorizontal",
    "barchart",
    "gauge",
    "warning",
    "error",
    "success",
    "settings",
    "globe",
    "repair",
    "info",
    "go",
    "blockedsite",
    "close",
    "circlefill",
    "circlering",
    "pinned",
    "pinnedfill",
    "unpin",
    "excel",
    "flag",
    "library",
    "mail",
    "lock",
    "piedouble",
    "rewind",
    "asterisk",
    "comment",
    "checkbox",
    "checkboxfill",
    "checkboxindeterminate",
    "checkboxreversed",
    "inserttextbox",
    "toggle",
    "togglefilled",
    "delete",
    "refresh",
    "miniexpand",
    "minicontract",
    "waffle",
    "filter",
    "filterfilled",
    "visualsinteraction",
    "crosshighlight",
    "crosshighlightfilled",
    "disable",
    "disablefilled",
    "export",
    "iframe",
    "addcircle",
    "fullscreen",
    "fullscreenexit",
    "fittopage",
    "code",
    "zorder",
    "visualinteraction",
    "alignment",
    "shapes",
    "attachment",
    "securityalert",
    "bold",
    "italics",
    "underline",
    "rectangle",
    "oval",
    "line",
    "triangle",
    "arrow",
    "image",
    "alignleft",
    "aligncenter",
    "alignright",
    "qrcode",
    "powerbi",
    "gear",
    "download",
    "smiley",
    "question",
    "tile",
    "rlogo",
    "play",
    "stop",
    "excelcloud",
    "importvisual",
    "sharepoint",
    "print",
    "stackedbar",
    "stackedcolumn",
    "areachart",
    "piechart",
    "fullstackedbar",
    "linechart",
    "scatter",
    "funnel",
    "dataset",
    "publishtoweb",
    "database",
    "drilltodetail",
    "seedata",
    "move",
    "home",
    "rotatehorizontal",
    "rotatevertical",
    "download2",
    "calculate",
    "reload",
    "insight",
    "nonetwork",
    "dynamic",
    "fittopage2",
    "fittowidth",
    "actualsize",
    "favoritefilled",
    "expand",
    "drillup",
    "drilldowndisabled",
    "drilldownenabled",
    "show",
    "bell",
    "atoz",
    "ztoa",
    "objectleft",
    "objectcenter",
    "objectright",
    "objecttop",
    "objectmiddle",
    "objectbottom",
    "bringtofront",
    "sendtoback",
    "bringforward",
    "bringbackward",
    "advancedfilter",
    "contentviewicon",
    "saveformobile",
    "phone",
    "user",
    "streaming-data",
    "refresh-data",
    "circled-checkmark",
    "play-alt",
    "pause",
    "barcode-scanner",
    "collections",
    "eraser",
    "arrowleft",
    "arrowright",
    "paintbrush",
    "notification-center",
    "sort",
    "realtime",


    "chevrondownmedium",
    "chevronupmedium",
    "caretdownright",

    "pin",
    "caretright",
    "caretdown",
    "caretleft",
    "chevronrightmedium",
    "chevronleftmedium",
    "uparrow",
    "rightarrow",
    "uprightarrow",
    "getdata",
    "cancel"
  ],
});


